# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test that the module imports
      id: install
      run: |
        pip install .
        python -c "import py4DSTEM; print(py4DSTEM.__version__)"
  test:

    needs: build
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test that the module imports
      id: install
      run: |
        pip install .
        python -c "import py4DSTEM; print(py4DSTEM.__version__)"
    - name: Checkout tutorials
      uses: actions/checkout@v3
      with:
        repository: mlhenderson/py4DSTEM_tutorials
        path: './py4DSTEM_tutorials'
    - name: Install tutorial dependencies
      run: |
        python -m pip install .
        python -m pip install "jedi==0.17.2" "dask[complete]" pymatgen gdown jupyter
    - name: Cache data files
      id: cache-data
      uses: actions/cache@v3
      env:
        cache-name: cache-data
      with:
        path: |
          ~/data
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('~/data/download_files.json') }}
    - if: ${{ steps.cache-data.outputs.cache-hit != 'true' }}
      name: Download tutorial data
      uses: jannekem/run-python-script-action@v1
      continue-on-error: true
      with:
        script: |
          import json
          import os
          import shutil

          import gdown
          from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError
          import nbformat

          data_dir = os.path.abspath(os.path.expandvars("~/data"))
          if not os.path.exists(data_dir):
              os.makedirs(data_dir)
          notebooks_dir = os.path.abspath("./py4DSTEM_tutorials/notebooks/")
          google_url = 'https://drive.google.com'
          downloads = {}
          notebooks = sorted([p.name for p in os.scandir(notebooks_dir) if '.ipynb' in p.name and p.is_file()])

          for nb_file in notebooks:
              downloads[nb_file] = []

              print("\tChecking for downloads and hardcoded paths in {}".format(nb_file))
              with open(os.path.join(notebooks_dir, nb_file), 'r') as f:
                  nb = nbformat.read(f, as_version=4)
                  for i in range(len(nb['cells'])):
                      text = nb['cells'][i]['source']
                      if google_url in text:
                          lines = text.split()
                          urls = [x.strip() for x in lines if google_url in x]
                          # download file
                          print("\tDownloading input files for {}".format(nb_file))
                          for u in urls:
                              download_url = u.split('(')[1][:-1]
                              name = gdown.download(url=download_url, fuzzy=True)
                              if name is not None:
                                  destination = os.path.join(data_dir, name)
                                  shutil.move(name, destination)
                                  downloads[nb_file].append(destination)
                              else:
                                  print("Unable to download {}".format(download_url))

          with open(os.path.join(data_dir, 'download_files.json'), 'w') as f:
              json.dump(downloads, f)
              print(json.dumps(downloads))
          print(os.listdir(data_dir))
    - name: Run tutorial notebooks
      uses: jannekem/run-python-script-action@v1
      continue-on-error: true
      with:
        script: |
          import json
          import os
          import re
          import sys
          import traceback

          from nbconvert.preprocessors import ExecutePreprocessor, CellExecutionError
          import nbformat

          data_dir = os.path.abspath(os.path.expandvars("~/data"))
          notebooks_dir = os.path.abspath("./py4DSTEM_tutorials/notebooks/")
          os.chdir(notebooks_dir)
          google_url = 'https://drive.google.com'
          with open(os.path.join(data_dir, 'download_files.json'), 'r') as f:
              downloads = json.load(f)
              print(downloads)
          notebooks = sorted([p.name for p in os.scandir(notebooks_dir) if '.ipynb' in p.name and p.is_file()])

          failed = []
          succeeded = []

          for nb_file in notebooks:
              print("Testing {}".format(nb_file))
              print("{} in downloads: {}, {}".format(nb_file, nb_file in downloads, downloads[nb_file]))
              changed = False

              print("\tChecking for downloads and hardcoded paths in {}".format(nb_file))
              with open(nb_file, 'r') as f:
                  nb = nbformat.read(f, as_version=4)
                  for i in range(len(nb['cells'])):
                      text = nb['cells'][i]['source']
                      if 'file_' in text:
                          print("Found file_ in {}".format(text))
                          results = re.finditer(r'file_\w+\s*=\s*[r]?[\'\"](.*)[\'\"]\s*', text)
                          for r in results:
                              print("matched regex: {}".format(r.group()))
                              name_matches = 0
                              print("possible filenames to insert: {}".format(downloads[nb_file]))
                              for fpath in downloads[nb_file]:
                                  fname = os.path.split(fpath)[-1]
                                  print("Filename without path: {}".format(fname))
                                  if fname in r.group():
                                      print("Inserting {}".format(fpath))
                                      name_matches += 1
                                      text = text[:r.span()[0]] + fpath + text[r.span()[1]:]
                                      changed = True
                                      break
                              #if name_matches == 0:
                              #    print("no matches, replacing with {}".format(os.path.split(r)[1]))
                              #    text = text.replace(r, "{}".format(os.path.split(r)[1]))
                      nb['cells'][i]['source'] = text
                      print('After replacements: {}'.format(text))

                  if changed:
                      print("\tWriting path updates back to {}".format(nb_file))
                      with open(nb_file, 'w', encoding='utf-8') as f:
                          nbformat.write(nb, f)

                  print("\tExecuting {}".format(nb_file))
                  try:
                      ep = ExecutePreprocessor(timeout=600, kernel_name='python3')
                      ep.preprocess(nb, {'metadata': {'path': notebooks_dir}})
                      succeeded.append(nb_file)
                  except Exception as e:
                      failed.append(nb_file)
                      tb = "\n".join(["\t{}".format(line) for line in traceback.format_exc().splitlines()])
                      print("\n\t{0} {1} {0}\n\n{2}\n\t{0} {1} {0}\n".format("*"*20, nb_file, tb))

          print("{} Notebooks ran without errors.".format(len(succeeded)))
          print("{} Notebooks failed with errors".format(len(failed)))
          if len(failed) > 0:
              sys.exit(-1)
          else:
              sys.exit(0)
